services:
  gophkeeper_auth:
    build:
      context: auth
      dockerfile: Dockerfile
    command: ./auth
    env_file:
      - deploy/auth.env
    depends_on:
      - "gophkeeper_auth_data"
    ports:
      - "8080:8080"
      - "9090:9090"
    restart: always

  gophkeeper_auth_data:
    image: postgres:17-alpine
    restart: always
    env_file:
      - deploy/auth.env
    ports:
      - "5555:5432"
    expose:
      - "5432"
    volumes:
      - ./data/gophkeeper_auth_data:/var/lib/postgresql/data

  gophkeeper:
    build:
      context: gophkeeper
      dockerfile: Dockerfile
    command: ./gophkeeper
    env_file:
      - deploy/gophkeeper.env
    depends_on:
      - "gophkeeper_data"
      - "gophkeeper_auth"
    ports:
      - "8081:8081"
      - "9091:9091"
    volumes:
      - ./data/user_files:/user_files
    restart: always

  gophkeeper_data:
    image: postgres:17-alpine
    restart: always
    env_file:
      - deploy/gophkeeper.env
    ports:
      - "5556:5432"
    expose:
      - "5432"
    volumes:
      - ./data/gophkeeper_data:/var/lib/postgresql/data
